language: node_js
node_js:
  - '10.16.3'
cache:
  directories:
    - node_modules
script:
  - echo "starting eslint with below extended config"
  - echo `cat .eslintrc`
  - echo "lint done"
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
